networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

  t1s1_net:
    name: t1s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.1.0/24

  t1s2_net:
    name: t1s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.1.0/24

  t2s1_net:
    name: t2s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.2.0/24

  t2s2_net:
    name: t2s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.2.0/24

  t3s1_net:
    name: t3s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.3.0/24

  t3s2_net:
    name: t3s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.3.0/24

x-ceos-defaults: &ceos-defaults
  image: arista-ceos:4.33.0F
  platform: linux/amd64
  environment:
    - INTFTYPE=eth
    - MGMT_INTF=eth0
    - MAPETH0=1
    - ETBA=1
    - SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
    - CEOS=1
    - EOS_PLATFORM=ceoslab
    - container=docker
  privileged: true
  command: >
    /sbin/init
    systemd.setenv=INTFTYPE=eth
    systemd.setenv=MGMT_INTF=eth0
    systemd.setenv=MAPETH0=1
    systemd.setenv=ETBA=1
    systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1
    systemd.setenv=CEOS=1
    systemd.setenv=EOS_PLATFORM=ceoslab
    systemd.setenv=container=docker

x-frr-defaults: &frr-defaults
  image: frrouting/frr:v8.4.1
  privileged: true
  networks:
    mgmt: {}
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  tty: true
  command: >
    sh -c "apk add --no-cache openssh sudo &&
           echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
           echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
           echo 'root:frr' | chpasswd &&
           adduser -h /home/annet -s /bin/sh -D annet &&
           echo 'annet ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers &&
           echo -n 'annet:annet' | chpasswd &&
           ssh-keygen -A &&
           /usr/sbin/sshd &&
           /sbin/tini -- /usr/lib/frr/docker-start"

services:
  netbox:
    container_name: netbox
    hostname: netbox
    ports:
      - 8000:8080
    volumes:
      - ../topologies/lab12_dc_arista_cisco_frr/src:/home/ubuntu/src

  annet:
    container_name: annet
    hostname: annet
    image: annet
    # since netbox required a lot of resources, but the lab emulators required them too,
    # to avoid issues that order was applied here and later
    depends_on:
      netbox:
        condition: service_healthy
    volumes:
      - ../annet/config.yaml:/config.yaml
      # lab 02 and lab03 uses the same lab_generators
      - ../topologies/lab12_dc_arista_cisco_frr/src/lab_generators:/lab_generators

  ceos-spine-1:
    <<: *ceos-defaults
    hostname: spine-1-1
    container_name: spine-1-1
    depends_on:
      netbox:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.20.0.101
      t1s1_net:
        ipv4_address: 10.1.1.11
      t2s1_net:
        ipv4_address: 10.1.2.11
      t3s1_net:
        ipv4_address: 10.1.3.11
    volumes:
      - ../topologies/lab12_dc_arista_cisco_frr/operational_configs/ceos-r2.flash:/mnt/flash/

  frr-r1:
    <<: *frr-defaults
    container_name: spine-1-2
    hostname: spine-1-2
    depends_on:
      netbox:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.20.0.102
      t1s2_net:
        ipv4_address: 10.2.1.11
      t2s2_net:
        ipv4_address: 10.2.2.11
      t3s2_net:
        ipv4_address: 10.2.3.11
    volumes:
      - ../topologies/lab12_dc_arista_cisco_frr/operational_configs/frr-r1.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r2:
    <<: *frr-defaults
    container_name: tor-1-2
    hostname: tor-1-2
    depends_on:
      netbox:
        condition: service_healthy
    networks:
      default:
        ipv4_address: 172.20.0.104
      t2s1_net:
        ipv4_address: 10.1.2.12
      t2s2_net:
        ipv4_address: 10.2.2.12
    volumes:
      - ../topologies/lab12_dc_arista_cisco_frr/operational_configs/frr-r2.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  dynamips-lab:
    container_name: dynamips
    hostname: dynamips
    depends_on:
      netbox:
        condition: service_healthy
    image: ubuntu:bionic
    tty: true
    volumes:
      - ../topologies/lab12_dc_arista_cisco_frr/src:/home/ubuntu/
      - ../vm_images:/home/ubuntu/vm_images
    command: sh "/home/ubuntu/install.sh"
    cap_add:
          - net_admin
          - net_raw
          - sys_module
    devices: [/dev/net/tun:/dev/net/tun]
    networks:
      - default  # br0 (eth0, tap0, tap1)
      - t1s1_net # br1 (eth1, tap2)
      - t1s2_net # br2 (eth2, tap3)
      - t3s1_net # br3 (eth3, tap4)
      - t3s2_net # br4 (eth4, tap5)
