networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/24
        gateway: 172.20.0.1

  t1s1_net:
    name: t1s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.1.0/24

  t1s2_net:
    name: t1s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.1.0/24

  t2s1_net:
    name: t2s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.2.0/24

  t2s2_net:
    name: t2s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.2.0/24

  t3s1_net:
    name: t3s1_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.1.3.0/24

  t3s2_net:
    name: t3s2_net
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.2.3.0/24

x-frr-defaults: &frr-defaults
  image: frrouting/frr:v8.4.1
  privileged: true
  networks:
    mgmt: {}
  cap_add:
    - NET_ADMIN
    - SYS_ADMIN
  sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.forwarding=1
    - net.ipv6.conf.all.forwarding=1
  tty: true
  command: >
    sh -c "apk add --no-cache openssh sudo &&
           echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
           echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
           echo 'root:frr' | chpasswd &&
           adduser -h /home/annet -s /bin/sh -D annet &&
           echo 'annet ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers &&
           echo -n 'annet:annet' | chpasswd &&
           ssh-keygen -A &&
           /usr/sbin/sshd &&
           /sbin/tini -- /usr/lib/frr/docker-start"

services:
  netbox:
    container_name: netbox
    hostname: netbox
    ports:
      - 8000:8080
    volumes:
      - ../topologies/lab11_dc_frr/src:/home/ubuntu/src

  annet:
    container_name: annet
    hostname: annet
    image: annet
    volumes:
      - ../annet/config.yaml:/config.yaml
      - ../topologies/lab11_dc_frr/src/lab_generators:/lab_generators

  frr-r1:
    <<: *frr-defaults
    container_name: spine-1-1
    hostname: spine-1-1
    networks:
      default:
        ipv4_address: 172.20.0.111
      t1s1_net:
        ipv4_address: 10.1.1.11
      t2s1_net:
        ipv4_address: 10.1.2.11
      t3s1_net:
        ipv4_address: 10.1.3.11
    volumes:
      - ../topologies/lab11_dc_frr/operational_configs/frr-r1.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r2:
    <<: *frr-defaults
    container_name: spine-1-2
    hostname: spine-1-2
    networks:
      default:
        ipv4_address: 172.20.0.112
      t1s2_net:
        ipv4_address: 10.2.1.11
      t2s2_net:
        ipv4_address: 10.2.2.11
      t3s2_net:
        ipv4_address: 10.2.3.11
    volumes:
      - ../topologies/lab11_dc_frr/operational_configs/frr-r2.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r3:
    <<: *frr-defaults
    container_name: tor-1-1
    hostname: tor-1-1
    networks:
      default:
        ipv4_address: 172.20.0.113
      t1s1_net:
        ipv4_address: 10.1.1.12
      t1s2_net:
        ipv4_address: 10.2.1.12
    volumes:
      - ../topologies/lab11_dc_frr/operational_configs/frr-r3.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r4:
    <<: *frr-defaults
    container_name: tor-1-2
    hostname: tor-1-2
    networks:
      default:
        ipv4_address: 172.20.0.114
      t2s1_net:
        ipv4_address: 10.1.2.12
      t2s2_net:
        ipv4_address: 10.2.2.12
    volumes:
      - ../topologies/lab11_dc_frr/operational_configs/frr-r4.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro

  frr-r5:
    <<: *frr-defaults
    container_name: tor-1-3
    hostname: tor-1-3
    networks:
      default:
        ipv4_address: 172.20.0.115
      t3s1_net:
        ipv4_address: 10.1.3.12
      t3s2_net:
        ipv4_address: 10.2.3.12
    volumes:
      - ../topologies/lab11_dc_frr/operational_configs/frr-r5.frr/frr.conf:/etc/frr/frr.conf
      - ../topologies/common_configs/frr_common_daemons:/etc/frr/daemons:ro
      - ../topologies/common_configs/frr_common_vtysh:/etc/frr/vtysh.conf:ro
